services:
  web:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'web.gitlab.local'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://web.gitlab.local'
        gitlab_rails['initial_root_password'] = "password"
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - './web/config:/etc/gitlab'
      - './web/logs:/var/log/gitlab'
      - './web/data:/var/opt/gitlab'
  runner:
    image: 'gitlab/gitlab-runner:latest'
    restart: always
    hostname: 'runner.gitlab.local'
    volumes:
      - './runner/config:/etc/gitlab-runner'
    links:
      - 'web'
